package com.dve.sari.theme

import androidx.compose.ui.graphics.Color

// Pokémon Light Theme Colors
val pokemon_light_primary = Color(0xFF4C9DFF)
val pokemon_light_onPrimary = Color(0xFFFFFFFF)
val pokemon_light_primaryContainer = Color(0xFFE6F0FF)
val pokemon_light_onPrimaryContainer = Color(0xFF003366)
val pokemon_light_secondary = Color(0xFFFFD700)
val pokemon_light_onSecondary = Color(0xFF1D1D00)
val pokemon_light_secondaryContainer = Color(0xFFFFF2A8)
val pokemon_light_onSecondaryContainer = Color(0xFF5E4400)
val pokemon_light_tertiary = Color(0xFFEF476F)
val pokemon_light_onTertiary = Color(0xFFFFFFFF)
val pokemon_light_tertiaryContainer = Color(0xFFF9A1B2)
val pokemon_light_onTertiaryContainer = Color(0xFF66000A)
val pokemon_light_error = Color(0xFFBA1A1A)
val pokemon_light_errorContainer = Color(0xFFFFDAD6)
val pokemon_light_onError = Color(0xFFFFFFFF)
val pokemon_light_onErrorContainer = Color(0xFF410002)
val pokemon_light_background = Color(0xFFFFFBFF)
val pokemon_light_onBackground = Color(0xFF1C1D00)
val pokemon_light_surface = Color(0xFFFFFBFF)
val pokemon_light_onSurface = Color(0xFF1C1D00)
val pokemon_light_surfaceVariant = Color(0xFFE6E3D1)
val pokemon_light_onSurfaceVariant = Color(0xFF48473A)
val pokemon_light_outline = Color(0xFF797869)
val pokemon_light_inverseOnSurface = Color(0xFFF5F77E)
val pokemon_light_inverseSurface = Color(0xFF313300)
val pokemon_light_inversePrimary = Color(0xFF4C9DFF)
val pokemon_light_surfaceTint = Color(0xFF4C9DFF)
val pokemon_light_outlineVariant = Color(0xFFCAC7B6)
val pokemon_light_scrim = Color(0xFF000000)

// Pokémon Dark Theme Colors
val pokemon_dark_primary = Color(0xFF4C9DFF)
val pokemon_dark_onPrimary = Color(0xFF003366)
val pokemon_dark_primaryContainer = Color(0xFF00264D)
val pokemon_dark_onPrimaryContainer = Color(0xFFE6F0FF)
val pokemon_dark_secondary = Color(0xFFFFD700)
val pokemon_dark_onSecondary = Color(0xFF5E4400)
val pokemon_dark_secondaryContainer = Color(0xFF5E4400)
val pokemon_dark_onSecondaryContainer = Color(0xFFFFF2A8)
val pokemon_dark_tertiary = Color(0xFFEF476F)
val pokemon_dark_onTertiary = Color(0xFF66000A)
val pokemon_dark_tertiaryContainer = Color(0xFF66000A)
val pokemon_dark_onTertiaryContainer = Color(0xFFF9A1B2)
val pokemon_dark_error = Color(0xFFFFB4AB)
val pokemon_dark_errorContainer = Color(0xFF93000A)
val pokemon_dark_onError = Color(0xFF690005)
val pokemon_dark_onErrorContainer = Color(0xFFFFDAD6)
val pokemon_dark_background = Color(0xFF1C1D00)
val pokemon_dark_onBackground = Color(0xFFE6E971)
val pokemon_dark_surface = Color(0xFF1C1D00)
val pokemon_dark_onSurface = Color(0xFFE6E971)
val pokemon_dark_surfaceVariant = Color(0xFF48473A)
val pokemon_dark_onSurfaceVariant = Color(0xFFCAC7B6)
val pokemon_dark_outline = Color(0xFF939182)
val pokemon_dark_inverseOnSurface = Color(0xFF1C1D00)
val pokemon_dark_inverseSurface = Color(0xFFE6E971)
val pokemon_dark_inversePrimary = Color(0xFF4C9DFF)
val pokemon_dark_surfaceTint = Color(0xFF4C9DFF)
val pokemon_dark_outlineVariant = Color(0xFF48473A)
val pokemon_dark_scrim = Color(0xFF000000)
